# -*- coding: utf-8 -*-
"""Tom_Jerry_Classification (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11z41tTxjyH6leFrfMo7pyr5Rnl57FFSa

# **OctWave 3.0 | Kaggle Challenge 02: Tom & Jerry Image Classification**
### **EDA** → **CSV Driven Data Pipeline** → **Transfer Learning** → **Fine Tuning** → **Evaluation** → **Submission**

**Author:** *Yasandu Kethmika*

**Evaluation Metric:** *Macro F1-score (each of the 4 classes weighted equally, regardless of frequency)*

**Task:** *Predict `appearance` for each test image, `0` = neither, `1` = Tom only, `2` = Jerry only, `3` = both.*

**Dataset structure (real, confirmed from the actual files):**
```
images/            <- ALL 5,481 images in ONE folder (train + test mixed together)
train.csv          <- filename, appearance   (2,680 labeled rows)
test.csv           <- filename                (2,798 rows to predict)
sample_submission.csv
```
This is **not** a folder per class layout, labels come from `train.csv`, so the data pipeline below
loads images by filename rather than by directory structure.



### **A Note on the Dataset and Expectations**
The organizers have mentioned that this dataset contains significant class imbalance and several challenging image conditions such as motion blur, partial occlusion, and similar looking backgrounds. Because of these issues, achieving a perfect Macro F1-score of 1.0 on unseen test data would not be a realistic expectation.

Therefore, throughout this notebook, I will focus on building a model that can generalize well to unseen images rather than simply achieving a very high score on the training data. I will also verify the important steps of the pipeline and try to make each modeling decision based on the characteristics of the dataset.
"""

from google.colab import drive
drive.mount('/content/drive')

# ===== Imports =====
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    f1_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
)
from sklearn.utils.class_weight import compute_class_weight

import warnings
warnings.filterwarnings("ignore")

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 100

RANDOM_STATE = 42
tf.random.set_seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices("GPU"))

"""## **1. Configuration & Metadata Loading**"""

DATA_DIR = "/content/drive/MyDrive/oct-wave-3-0-kaggle-challenge-02"

IMAGES_DIR = os.path.join(DATA_DIR, "images", "images")
TRAIN_CSV = os.path.join(DATA_DIR, "train.csv")
TEST_CSV = os.path.join(DATA_DIR, "test.csv")
SAMPLE_SUB_CSV = os.path.join(DATA_DIR, "sample_submission.csv")

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

CLASS_LABELS = [0, 1, 2, 3]
CLASS_NAMES = ["neither", "tom_only", "jerry_only", "both"]

print("Dataset directory:", DATA_DIR)
print("train.csv:", TRAIN_CSV)
print("images:", IMAGES_DIR)

print("\nChecking files...")
print("train.csv exists:", os.path.isfile(TRAIN_CSV))
print("test.csv exists:", os.path.isfile(TEST_CSV))
print("sample_submission.csv exists:", os.path.isfile(SAMPLE_SUB_CSV))
print("images folder exists:", os.path.isdir(IMAGES_DIR))

assert os.path.isfile(TRAIN_CSV), f"train.csv not found at {TRAIN_CSV}"
assert os.path.isdir(IMAGES_DIR), f"images/ folder not found at {IMAGES_DIR}"

train_meta = pd.read_csv(TRAIN_CSV)
test_meta = pd.read_csv(TEST_CSV)
sample_submission = pd.read_csv(SAMPLE_SUB_CSV)

print("\nTrain metadata:", train_meta.shape)
print("Test metadata :", test_meta.shape)

train_meta.head()

# Sanity checks
print("Missing values in train_meta:\n", train_meta.isna().sum())
print("Duplicate filenames in train:", train_meta['filename'].duplicated().sum())
print("Any overlap between train/test filenames:",
      len(set(train_meta.filename) & set(test_meta.filename)))

# Confirm every referenced image actually exists on disk
missing_train_imgs = [f for f in train_meta['filename'] if not os.path.isfile(os.path.join(IMAGES_DIR, f))]
missing_test_imgs = [f for f in test_meta['filename'] if not os.path.isfile(os.path.join(IMAGES_DIR, f))]
print(f"\nMissing train images: {len(missing_train_imgs)}")
print(f"Missing test images : {len(missing_test_imgs)}")
if missing_train_imgs:
    print("Example missing:", missing_train_imgs[:5])

"""## **2. Exploratory Data Analysis**

### **2.1 Class Distribution**
First, I want to check how the training images are distributed among the four classes. This is important because the dataset is expected to have a significant class imbalance, and the competition uses Macro F1-score as the evaluation metric.

If one class has many more samples than the others, the model may become biased towards that class. Therefore, I will also calculate the imbalance ratio and consider using class weights during training to give more importance to the minority classes.
"""

class_counts = train_meta['appearance'].value_counts().sort_index()
class_pct = train_meta['appearance'].value_counts(normalize=True).sort_index() * 100

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

bars = axes[0].bar([CLASS_NAMES[i] for i in class_counts.index], class_counts.values,
                    color=sns.color_palette("viridis", len(class_counts)))
axes[0].set_title("Training Image Count per Class", fontweight="bold")
axes[0].set_ylabel("Count")
for bar, v in zip(bars, class_counts.values):
    axes[0].text(bar.get_x() + bar.get_width()/2, v + 10, str(v), ha="center", fontweight="bold")

axes[1].pie(class_pct.values, labels=[CLASS_NAMES[i] for i in class_pct.index],
            autopct="%1.1f%%", colors=sns.color_palette("viridis", len(class_pct)), startangle=90)
axes[1].set_title("Class Distribution (%)", fontweight="bold")

plt.tight_layout()
plt.show()

print(class_counts)
imbalance_ratio = class_counts.max() / class_counts.min()
print(f"\nImbalance ratio (largest / smallest class): {imbalance_ratio:.2f}x")
print("-> We'll use class weighting during training (Section 5) to counter this.")

"""### **Observation**

The class distribution confirms that the dataset is highly imbalanced. The tom_only class is the majority class with 1,252 images, while the both class has only 219 images. The largest-to-smallest class ratio is approximately 5.72×. This imbalance needs to be considered during model training, especially because Macro F1 gives equal importance to all four classes.

### **2.2 Sample Images per Class**
Before moving on to the model, I want to look at some actual images from each class. This helps me understand what the images look like and identify any visible differences between the classes.

It can also help reveal issues such as blurred images, partial occlusions, unusual backgrounds, or images where the class label may be difficult to distinguish. This gives me a better idea of the challenges the model will have to handle during training.
"""

fig, axes = plt.subplots(len(CLASS_LABELS), 5, figsize=(15, 3 * len(CLASS_LABELS)))

for row, label in enumerate(CLASS_LABELS):
    sample_files = train_meta[train_meta['appearance'] == label]['filename'].sample(
        min(5, (train_meta['appearance'] == label).sum()), random_state=RANDOM_STATE
    )
    for col, fname in enumerate(sample_files):
        img = Image.open(os.path.join(IMAGES_DIR, fname))
        ax = axes[row, col]
        ax.imshow(img)
        ax.axis("off")
        if col == 0:
            ax.set_title(f"{CLASS_NAMES[label]} ({label})", fontsize=11, fontweight="bold", loc="left")

plt.suptitle("Sample Images per Class", fontsize=14, fontweight="bold", y=1.0)
plt.tight_layout()
plt.show()

"""### **2.3 Image Size Consistency & Corrupt File Check**
Before starting the training process, I also want to check whether the images have consistent dimensions and whether any of the image files are corrupted or cannot be opened properly. Since these images come from extracted video frames, their sizes are expected to be mostly consistent, but it is still important to verify this before building the data pipeline.

A corrupted image or unexpected image size could cause problems later when loading batches during training. Checking this now helps avoid such issues during the model training stage.
"""

sizes = []
corrupt_files = []
sample_check = train_meta.sample(min(300, len(train_meta)), random_state=RANDOM_STATE)

for fname in sample_check['filename']:
    fpath = os.path.join(IMAGES_DIR, fname)
    try:
        with Image.open(fpath) as img:
            img.verify()
        with Image.open(fpath) as img:
            w, h = img.size
            sizes.append({"filename": fname, "width": w, "height": h})
    except Exception:
        corrupt_files.append(fpath)

sizes_df = pd.DataFrame(sizes)
print(sizes_df[["width", "height"]].describe())
print(f"\nCorrupt/unreadable images (sampled {len(sample_check)}): {len(corrupt_files)}")
if corrupt_files:
    print("Example:", corrupt_files[:5])

"""### **Observation**

The sampled images have different resolutions, mainly 854 × 480, with some images having a resolution of 1280 × 720. However, the aspect ratio is consistent with the images being extracted from video frames. No corrupt or unreadable images were found among the 300 randomly sampled training images. Since the model will use a fixed input size of 224 × 224, the images will be resized during preprocessing before being passed to the model.

## **3. Stratified Train/Validation Split**

Since the dataset has a noticeable class imbalance, I need to make sure that the training and validation sets have a similar distribution of all four classes. For this reason, I will use a stratified split instead of a completely random split.

This is especially important for the ```both class```, which has the fewest training samples. A normal random split could result in too few examples of this class in the validation set, making its F1-score less reliable. Stratification helps maintain a similar class distribution in both sets and gives a fairer evaluation of the model.
"""

train_files, val_files = train_test_split(
    train_meta,
    test_size=0.15,
    stratify=train_meta['appearance'],
    random_state=RANDOM_STATE,
)

print("Train split:", train_files.shape)
print("Val split  :", val_files.shape)
print("\nTrain class distribution:\n", train_files['appearance'].value_counts(normalize=True).sort_index())
print("\nVal class distribution:\n", val_files['appearance'].value_counts(normalize=True).sort_index())

"""### **Observation**

The dataset was split into 2,278 training images and 402 validation images, using a 15% validation split. The class proportions in both sets are almost identical to the original distribution, including the minority both class. Therefore, the stratified split provides a more reliable validation set for evaluating the model, especially for the Macro F1-score.
"""

oversample_multiplier = {0: 3, 1: 1, 2: 1, 3: 4}
oversampled_frames = [train_files]
for class_label, multiplier in oversample_multiplier.items():
    if multiplier > 1:
        extra_copies = train_files[train_files['appearance'] == class_label]
        for _ in range(multiplier - 1):
            oversampled_frames.append(extra_copies)
train_files = pd.concat(oversampled_frames, ignore_index=True)
print("New train class distribution after oversampling:")
print(train_files['appearance'].value_counts().sort_index())

"""## **4. CSV Driven Data Pipeline**

Since the class labels are provided in ```train.csv``` instead of being separated into different folders, I need to create the data pipeline based on the filename and label pairs in the CSV file. The pipeline will use each filename to locate the corresponding image, load it, and then prepare it with the required preprocessing before passing it to the model.

Using ```tf.data.Dataset``` will also make it easier to load the images in batches and efficiently feed them into the model during training.
"""

def load_image(filename, label=None):
    path = tf.strings.join([IMAGES_DIR, filename], separator=os.sep)
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMG_SIZE)
    if label is not None:
        return img, label
    return img

def make_dataset(df, training=False, has_labels=True, batch_size=BATCH_SIZE):
    filenames = df['filename'].values
    if has_labels:
        labels = df['appearance'].values.astype('int32')
        ds = tf.data.Dataset.from_tensor_slices((filenames, labels))
        ds = ds.map(lambda f, l: load_image(f, l), num_parallel_calls=tf.data.AUTOTUNE)
    else:
        ds = tf.data.Dataset.from_tensor_slices(filenames)
        ds = ds.map(lambda f: load_image(f), num_parallel_calls=tf.data.AUTOTUNE)

    if training:
        ds = ds.shuffle(1000, seed=RANDOM_STATE)

    ds = ds.batch(batch_size)
    ds = ds.prefetch(tf.data.AUTOTUNE)
    return ds

train_ds_raw = make_dataset(train_files, training=True)
val_ds_raw = make_dataset(val_files, training=False)

# Quick shape check
for imgs, labels in train_ds_raw.take(1):
    print("Batch image shape:", imgs.shape, " Batch label shape:", labels.shape)

"""### **4.1 Data Augmentation**
To improve the model's ability to generalize to new images, I will apply data augmentation only to the training data. Since the dataset contains noisy frames and variations in the way Tom and Jerry appear in the images, small changes such as flipping, rotation, and zooming can help the model learn more robust visual features.

The validation and test images will not be augmented, so their original visual information can be used for a fair evaluation of the model.
"""

data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.08),
    layers.RandomZoom(0.1),
    layers.RandomContrast(0.15),
    layers.RandomBrightness(0.1),
], name="augmentation")

def prep_train(ds):
    return ds.map(lambda x, y: (data_augmentation(x, training=True), y),
                  num_parallel_calls=tf.data.AUTOTUNE).prefetch(tf.data.AUTOTUNE)

train_ds = prep_train(train_ds_raw)
val_ds = val_ds_raw  # no augmentation at validation time

"""### **4.2 Visualize Augmented Samples**"""

plt.figure(figsize=(12, 6))
for images, labels in train_ds_raw.take(1):
    for i in range(min(9, len(images))):
        ax = plt.subplot(3, 3, i + 1)
        augmented = data_augmentation(tf.expand_dims(images[i], 0), training=True)
        plt.imshow(augmented[0].numpy().astype("uint8"))
        plt.title(CLASS_NAMES[int(labels[i])])
        plt.axis("off")
plt.suptitle("Augmented Training Samples", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

"""## **5. Class Weighting**
The training data has a noticeable class imbalance, so I will use class weights during training to give more importance to the minority classes. The weights are calculated using only the training split, based on the actual number of samples available for each class.

As expected, the ```both``` class receives the highest weight because it has the fewest samples, while the ```tom_only``` class receives the lowest weight because it is the majority class. This should help reduce the model's bias towards the more frequent classes and improve its performance on the Macro F1-score.
"""

class_weights_array = compute_class_weight(
    class_weight="balanced",
    classes=np.array(CLASS_LABELS),
    y=train_files['appearance'].values
)
class_weights = dict(enumerate(class_weights_array))
print("Class weights (higher = rarer class, weighted more in the loss):")
for i, w in class_weights.items():
    print(f"  {CLASS_NAMES[i]} ({i}): {w:.3f}")

def sparse_categorical_focal_loss(gamma=2.0):
    def loss_fn(y_true, y_pred):
        y_true = tf.cast(y_true, tf.int32)
        y_pred = tf.clip_by_value(y_pred, 1e-7, 1 - 1e-7)
        ce = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
        p_t = tf.gather(y_pred, y_true, batch_dims=1)
        focal_weight = tf.pow(1 - p_t, gamma)
        return focal_weight * ce
    return loss_fn

"""## **6. Model: Transfer Learning with EfficientNetB0**

For this classification task, I am using ***EfficientNetB0*** with ImageNet pretrained weights. Since the available labeled dataset is relatively small, training the complete network from scratch would not be an ideal approach.

In the first stage, I keep the EfficientNetB0 backbone frozen and train only the newly added classification layers. This allows the model to make use of the visual features learned from ImageNet while learning a new classifier specifically for the four Tom & Jerry classes.

The second stage will involve unfreezing selected higher layers of the backbone and fine-tuning them with a much smaller learning rate so that the pretrained features can gradually adapt to this dataset.
"""

num_classes = len(CLASS_LABELS)

base_model = keras.applications.EfficientNetB0(
    include_top=False, weights="imagenet", input_shape=IMG_SIZE + (3,)
)
base_model.trainable = False

inputs = keras.Input(shape=IMG_SIZE + (3,))
x = keras.applications.efficientnet.preprocess_input(inputs)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.35)(x)
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.2)(x)
outputs = layers.Dense(num_classes, activation="softmax")(x)

model = keras.Model(inputs, outputs)
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss=sparse_categorical_focal_loss(gamma=2.0),
    metrics=["accuracy"],
)
model.summary()

"""### **6.1 Stage A - Train the Classification Head (Backbone Frozen)**"""

callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True),
    keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2, min_lr=1e-6),
]

EPOCHS_STAGE_A = 20

history_a = model.fit(
    train_ds, validation_data=val_ds, epochs=EPOCHS_STAGE_A,
    class_weight=class_weights, callbacks=callbacks,
)

"""### **6.2 Stage B - Fine Tune the Top Layers**"""

base_model.trainable = True
fine_tune_at = len(base_model.layers) - 30
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-5),
    loss=sparse_categorical_focal_loss(gamma=2.0),
    metrics=["accuracy"],
)

EPOCHS_STAGE_B = 12

history_b = model.fit(
    train_ds, validation_data=val_ds, epochs=EPOCHS_STAGE_B,
    class_weight=class_weights, callbacks=callbacks,
)

"""## **7. Training Curves**
After training the model, I will use the training and validation curves to see how the model's performance changes over time. Looking at both loss and accuracy helps me understand whether the model is learning properly and whether it starts to overfit the training data.

These curves will also help me compare the behavior of the model across the two training stages and decide whether further training is useful.
"""

acc = history_a.history["accuracy"] + history_b.history["accuracy"]
val_acc = history_a.history["val_accuracy"] + history_b.history["val_accuracy"]
loss = history_a.history["loss"] + history_b.history["loss"]
val_loss = history_a.history["val_loss"] + history_b.history["val_loss"]
stage_boundary = len(history_a.history["accuracy"])

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
axes[0].plot(acc, label="Train Accuracy"); axes[0].plot(val_acc, label="Val Accuracy")
axes[0].axvline(stage_boundary, linestyle="--", color="gray", label="Fine-tuning starts")
axes[0].set_title("Accuracy over Training"); axes[0].set_xlabel("Epoch"); axes[0].legend()

axes[1].plot(loss, label="Train Loss"); axes[1].plot(val_loss, label="Val Loss")
axes[1].axvline(stage_boundary, linestyle="--", color="gray", label="Fine-tuning starts")
axes[1].set_title("Loss over Training"); axes[1].set_xlabel("Epoch"); axes[1].legend()

plt.tight_layout()
plt.show()

"""### **7.1 Learning Rate Schedule**
Since I am using a two stage training strategy, the learning rate will also be different between the two stages. I will visualize the learning rate used during training to clearly see this change.

A relatively higher learning rate is used in the first stage to allow the newly added classification head to learn quickly. During fine tuning, the learning rate is reduced significantly so that the pretrained EfficientNet features can be adjusted gradually without making large updates that could damage the useful features already learned by the model.
"""

lr_a = history_a.history.get("learning_rate", [1e-3] * len(history_a.history["accuracy"]))
lr_b = history_b.history.get("learning_rate", [1e-5] * len(history_b.history["accuracy"]))
lr_schedule = list(lr_a) + list(lr_b)

plt.figure(figsize=(9, 4.5))
plt.plot(lr_schedule, marker="o", markersize=3, color="#E63946")
plt.axvline(stage_boundary, linestyle="--", color="gray", label="Fine-tuning starts")
plt.yscale("log")
plt.xlabel("Epoch")
plt.ylabel("Learning Rate (log scale)")
plt.title("Learning Rate Schedule Across Both Training Stages")
plt.legend()
plt.tight_layout()
plt.show()

"""## **8. Evaluation on Validation Set**
Since the competition uses Macro F1-score as the main evaluation metric, I will focus on Macro F1 rather than relying only on accuracy. This is especially important because the dataset is imbalanced and all four classes should have equal importance in the final evaluation.

I will evaluate the model on the validation set using the Macro F1-score, along with the classification report and confusion matrix, to get a better understanding of how well the model performs on each individual class.
"""

val_true = val_files['appearance'].values
val_pred_proba = model.predict(val_ds)
val_pred = np.argmax(val_pred_proba, axis=1)

macro_f1 = f1_score(val_true, val_pred, average="macro")
print(f"Validation Macro F1-score: {macro_f1:.4f}\n")
print(classification_report(val_true, val_pred, target_names=CLASS_NAMES, digits=4))

"""### **8.1 Confusion Matrix**
The confusion matrix will help me see how the model's predictions are distributed across the four classes. It shows which classes are being predicted correctly and where the model is making mistakes.

This is particularly useful for identifying cases where the model confuses similar classes, such as ```tom_only``` and ```both```, or ```jerry_only``` and ```both```. It gives a more detailed view of the model's performance than a single Macro F1-score.
"""

cm = confusion_matrix(val_true, val_pred, labels=CLASS_LABELS)
fig, ax = plt.subplots(figsize=(6.5, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=CLASS_NAMES)
disp.plot(ax=ax, cmap="Blues", colorbar=False, xticks_rotation=45)
ax.set_title("Confusion Matrix (Validation Set)")
plt.tight_layout()
plt.show()

"""### **8.2 Per Class F1 Breakdown**
Since Macro F1 gives equal importance to all four classes, I will also look at the F1-score of each class separately. This helps me understand where the model is performing well and which classes are more difficult to predict.

In particular, I will pay attention to the ```both``` class because it has the fewest training samples. However, I will use the actual validation results to determine which class needs the most improvement rather than assuming it beforehand.
"""

per_class_f1 = f1_score(val_true, val_pred, average=None, labels=CLASS_LABELS)
per_class_df = pd.DataFrame({"class": CLASS_NAMES, "f1_score": per_class_f1,
                              "n_val_samples": [np.sum(val_true == l) for l in CLASS_LABELS]}).sort_values("f1_score")

plt.figure(figsize=(8, 5))
colors = ["#E63946" if f < macro_f1 else "#2E86AB" for f in per_class_df["f1_score"]]
bars = plt.barh(per_class_df["class"], per_class_df["f1_score"], color=colors)
plt.axvline(macro_f1, linestyle="--", color="black", label=f"Macro F1 = {macro_f1:.3f}")
plt.xlabel("F1-score"); plt.title("Per-Class F1-score (red = below average)"); plt.legend()
for bar, v in zip(bars, per_class_df["f1_score"]):
    plt.text(v + 0.01, bar.get_y() + bar.get_height()/2, f"{v:.3f}", va="center", fontweight="bold")
plt.tight_layout()
plt.show()
print(per_class_df)

"""### **8.3 Precision & Recall per Class**
The F1-score gives an overall view of a class's performance, but it does not show exactly where the mistakes are coming from. Therefore, I will also look at precision and recall for each class.

A low precision means the model is predicting that class too often and producing more false positives. A low recall means the model is missing actual examples of that class. Looking at both values helps me understand the type of errors the model is making and why a particular class may have a lower F1-score.
"""

from sklearn.metrics import precision_score, recall_score

precision_per_class = precision_score(val_true, val_pred, average=None, labels=CLASS_LABELS, zero_division=0)
recall_per_class = recall_score(val_true, val_pred, average=None, labels=CLASS_LABELS, zero_division=0)

pr_df = pd.DataFrame({
    "class": CLASS_NAMES,
    "precision": precision_per_class,
    "recall": recall_per_class,
    "f1": per_class_f1,
    "n_val_samples": [np.sum(val_true == l) for l in CLASS_LABELS],
})
print(pr_df)

fig, ax = plt.subplots(figsize=(9, 5))
x = np.arange(len(CLASS_NAMES))
width = 0.35
ax.bar(x - width/2, pr_df["precision"], width, label="Precision", color="#2E86AB")
ax.bar(x + width/2, pr_df["recall"], width, label="Recall", color="#E63946")
ax.set_xticks(x)
ax.set_xticklabels(CLASS_NAMES)
ax.set_ylabel("Score")
ax.set_title("Precision vs Recall per Class")
ax.legend()
plt.tight_layout()
plt.show()

"""### **8.4 Misclassified Examples**"""

val_images_list = []
for imgs, labels in val_ds_raw:
    val_images_list.append(imgs.numpy())
val_images = np.concatenate(val_images_list)

misclassified_idx = np.where(val_true != val_pred)[0]
print(f"Total misclassified: {len(misclassified_idx)} / {len(val_true)}")

n_show = min(9, len(misclassified_idx))
if n_show > 0:
    fig, axes = plt.subplots(3, 3, figsize=(12, 12))
    axes = axes.flatten()
    for i, idx in enumerate(misclassified_idx[:n_show]):
        axes[i].imshow(val_images[idx].astype("uint8"))
        axes[i].set_title(f"True: {CLASS_NAMES[val_true[idx]]}\nPred: {CLASS_NAMES[val_pred[idx]]}", fontsize=10)
        axes[i].axis("off")
    for i in range(n_show, 9):
        axes[i].axis("off")
    plt.suptitle("Misclassified Validation Examples", fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.show()

"""## **8.5 What Is the Model Looking At? (Grad CAM Attention Check)**

To better understand how the model is making its predictions, I will use Grad-CAM to visualize the regions of an image that contribute most to the predicted class.

This helps me check whether the model is actually focusing on meaningful areas, such as Tom and Jerry, rather than relying on unrelated features like the background, colors, or other visual artifacts. It provides an additional way to verify whether the model has learned useful visual patterns for this classification task.
"""

def get_gradcam_heatmap(img_array, model, base_model, last_conv_layer_name=None):
    if last_conv_layer_name is None:
        for layer in reversed(base_model.layers):
            if len(layer.output.shape) == 4:
                last_conv_layer_name = layer.name
                break

    grad_model = keras.Model([base_model.input], [base_model.get_layer(last_conv_layer_name).output, base_model.output])

    with tf.GradientTape() as tape:
        conv_output, predictions = grad_model(img_array)
        pooled = layers.GlobalAveragePooling2D()(predictions)
        top_class = tf.argmax(pooled[0])
        class_channel = pooled[:, top_class]

    grads = tape.gradient(class_channel, conv_output)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    conv_output = conv_output[0]
    heatmap = conv_output @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0) / (tf.math.reduce_max(heatmap) + 1e-8)
    return heatmap.numpy()

# Show Grad-CAM for a few correctly-classified validation examples, one per class where possible
fig, axes = plt.subplots(2, min(4, num_classes), figsize=(4 * min(4, num_classes), 8))
shown = 0
for label in CLASS_LABELS:
    if shown >= 4:
        break
    correct_idx = np.where((val_true == label) & (val_pred == label))[0]
    if len(correct_idx) == 0:
        continue
    idx = correct_idx[0]
    try:
        sample_img = val_images[idx:idx+1]
        preprocessed = keras.applications.efficientnet.preprocess_input(sample_img.copy())
        heatmap = get_gradcam_heatmap(preprocessed, model, base_model)

        axes[0, shown].imshow(val_images[idx].astype("uint8"))
        axes[0, shown].set_title(f"{CLASS_NAMES[label]}\n(Original)", fontsize=10)
        axes[0, shown].axis("off")

        axes[1, shown].imshow(val_images[idx].astype("uint8"))
        axes[1, shown].imshow(heatmap, cmap="jet", alpha=0.5, extent=(0, IMG_SIZE[0], IMG_SIZE[1], 0))
        axes[1, shown].set_title("Grad-CAM Attention", fontsize=10)
        axes[1, shown].axis("off")
        shown += 1
    except Exception as e:
        print(f"Grad-CAM skipped for class {label}: {e}")

plt.suptitle("Grad-CAM: Where the Model Is Looking (Correct Predictions, One per Class)", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

"""## **9. Predict on Test Set (with Test Time Augmentation)**

For the final test predictions, I will use ***Test Time Augmentation (TTA)*** to make the predictions a little more robust. Instead of using only the original version of each test image, the model will also predict on a few augmented versions of the same image.

The predictions from these versions will then be averaged to obtain the final class probabilities. This can help reduce the effect of small variations or noise in individual frames and may provide a small improvement in the final performance.

Since the augmentation pipeline has already been defined earlier, I can reuse it for TTA without introducing a separate preprocessing approach.
"""

test_ds_raw = make_dataset(test_meta, training=False, has_labels=False, batch_size=BATCH_SIZE)

def predict_with_tta(model, ds_raw, n_augmentations=5):
    all_preds = []

    # 1. Clean (non-augmented) pass
    base_preds = model.predict(ds_raw)
    all_preds.append(base_preds)

    # 2. Several augmented passes, averaged in
    for _ in range(n_augmentations):
        aug_ds = ds_raw.map(lambda x: data_augmentation(x, training=True))
        aug_preds = model.predict(aug_ds)
        all_preds.append(aug_preds)

    return np.mean(all_preds, axis=0)

test_pred_proba = predict_with_tta(model, test_ds_raw, n_augmentations=5)
test_pred = np.argmax(test_pred_proba, axis=1)

print("Predicted test class distribution:")
print(pd.Series(test_pred).map(dict(enumerate(CLASS_NAMES))).value_counts())

"""### **9.1 Visual Sanity Check on Test Predictions**
Before creating the final submission, I will visually inspect a few test images together with their predicted classes. This provides a quick sanity check to make sure the predictions look reasonable and that the test time preprocessing and prediction pipeline are working as expected.

This is not a replacement for the validation metrics, but it can help identify obvious prediction or preprocessing issues before submitting the results.
"""

test_images_list = []
for imgs in test_ds_raw:
    test_images_list.append(imgs.numpy())
test_images = np.concatenate(test_images_list)

fig, axes = plt.subplots(2, 5, figsize=(16, 7))
axes = axes.flatten()
sample_idx = np.random.RandomState(RANDOM_STATE).choice(len(test_images), 10, replace=False)
for i, idx in enumerate(sample_idx):
    axes[i].imshow(test_images[idx].astype("uint8"))
    axes[i].set_title(f"Predicted: {CLASS_NAMES[test_pred[idx]]}", fontsize=10)
    axes[i].axis("off")
plt.suptitle("Sample Test Predictions", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

"""## **10. Generate Submission File**
Columns match `sample_submission.csv` exactly: `filename`, `appearance`.
"""

submission = pd.DataFrame({
    "filename": test_meta["filename"].values,
    "appearance": test_pred,
})

# Sanity checks before saving
assert submission.shape[0] == sample_submission.shape[0], "Row count mismatch!"
assert set(submission["filename"]) == set(sample_submission["filename"]), "Filename mismatch!"
assert set(submission["appearance"].unique()).issubset(set(CLASS_LABELS)), "Invalid class labels!"

submission.to_csv("submission.csv", index=False)
print("Submission saved.")
submission.head()

from google.colab import files
files.download('submission.csv')

"""## **11. Save the Trained Model**"""

model.save("tom_jerry_classifier.keras")
print("Model saved as tom_jerry_classifier.keras")

"""## **12. Methodology Summary**

**Task:**

This project focuses on 4-class image classification of cartoon frames into ```neither```, ```Tom only```, ```Jerry only```, and ```both```. The competition uses Macro F1-score as the main evaluation metric, so all four classes need to be considered equally despite the class imbalance.

**Data:**

The dataset contains 2,680 labeled training images and 2,798 test images. Image filenames and labels are provided through ```train.csv``` and ```test.csv```, while all images are stored in a shared ```images/``` directory. The dataset was checked to make sure the required files exist and the referenced images can be loaded correctly.

**Preprocessing & Augmentation:**

All images are resized to 224×224 before being passed to the model. During training, random horizontal flipping, rotation, zoom, contrast, and brightness changes are applied to make the model more robust to variations and noise in the image frames. Validation images are kept unchanged.

**Class Imbalance Handling:**

The training data contains a noticeable class imbalance, with ```tom_only``` being the most common class and ```both``` being the least common. Balanced class weights are calculated from the training split and used during model training so that the minority classes have a stronger influence on the loss.

**Validation Strategy:**

The labeled data is divided using an 85/15 stratified train-validation split. Stratification keeps the class proportions almost identical in both sets, which provides a more reliable evaluation, especially for the minority ```both``` class.

**Model:**

I use EfficientNetB0 pretrained on ImageNet as the backbone. The pretrained feature extractor is followed by Global Average Pooling, Dropout, Dense(128), another Dropout layer, and a final 4-class softmax layer.

**Training Strategy:**

Training is performed in two stages:

**Feature Extraction:**
The EfficientNetB0 backbone is frozen and only the new classification head is trained using Adam with a learning rate of ```1e-3```.

***Fine-Tuning:*** The top layers of the pretrained backbone are unfrozen and fine-tuned using a much smaller learning rate of ```1e-5```.

Early stopping and learning rate reduction are used to help control overfitting and avoid unnecessary training.

**Evaluation:**

The model is evaluated mainly using Macro F1-score on the held out validation set. I also use the confusion matrix and per class precision, recall, and F1-score to understand the model's strengths and weaknesses across the four classes. Grad-CAM is used to visually inspect whether the model is focusing on relevant regions of the images.

**Inference:**

For the final test predictions, Test Time Augmentation (TTA) is used. The model predicts the original image along with several augmented versions, and the resulting probabilities are averaged to obtain the final prediction. This is intended to make the predictions more robust to variations and noise in the test frames.

**Reproducibility:**
A fixed ```RANDOM_STATE = 42``` is used throughout the workflow so that the data split, sampling, and other randomized operations can be reproduced.
"""

import os
print("Current directory:", os.getcwd())
print("Files here:", os.listdir())

